nodejs/core-validate-commit

commit.js, test.js
Git log can be invoked with `git log --format=fuller` or `git log --pretty=fuller`. This can be set as default with `git config format.pretty fuller`.
`core-validate-commit` currently fails with `EMISSINGDATE` when this is set, this PR adds support and changes one of the tests to that format.
=> commit: support git config format.pretty fuller

bin/cmd.js
Fixes: #4
Possibly related: #1
This ensures that `git show` always returns results in the same format, rather than depending on the user's .gitconfig.
I didn't see any tests for the interface with git, but let me know if there's a place I should add some.
=> Don't throw an error if the user's git config uses a custom format

README.md, bin/cmd.js, bin/usage.txt, lib/utils.js
It is useful to know what rules exist. In the future, these need to be
documented.
Semver: minor
=> bin: add --list flag to list all rules

.travis.yml, lib/format-pretty.js, lib/rules/title-length.js, package-lock.json, package.json, test/validator.js
if https://github.com/nodejs/node/pull/16523 lands
=> warn for 50 < title <= 72

lib/rules/line-after-title.js, test/rules/line-after-title.js
Add tests for line-after-title.
Change line-after-title so that it does not report an error for commit messages that are a title line only.
=> tests and bugfix for line-after-title

lib/rules/line-length.js, test/rules/line-length.js, test/validator.js
Fixes: https://github.com/nodejs/core-validate-commit/issues/24
=> rules: skip line-length rule for URLs and quoted lines

lib/rules/title-format.js, test/rules/title-format.js
- Do not allow consecutive spaces
- Require a space after the subsystems
=> rules: check spaces in commit title

package-lock.json
This is to get out in front of
https://nvd.nist.gov/vuln/detail/CVE-2018-16487.
This also updates extend to get out in front of https://nvd.nist.gov/vuln/detail/CVE-2018-16492.
=> update lodash to 4.17.11 in package-lock.json

lib/rules/title-format.js, test/rules/title-format.js
The first colon denotes the subsystem(s). Any further colons are part
of the title and should not be subject to the rule that the following
word be in lowercase.
Refs: https://github.com/nodejs/node/pull/26308#issuecomment-467670622
=> rules: only check case of first word after subsystem

package-lock.json
```console
-bash-4.2$ npm audit
=== npm audit security report ===
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ handlebars                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ tap [dev]                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ tap > nyc > istanbul-reports > handlebars                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ …
```
=> Fix `npm audit` warning for handlebars

test/rules/reviewers.js, test/rules/subsystem.js
Covers uncovered lines in `reviewers.js` and `subsystems.js` reported in the coverage report.
Before
```console
--------------------------------|----------|----------|----------|----------|-------------------|
File                            |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
--------------------------------|----------|----------|----------|----------|-------------------|
All files                       |    95.57 |     88.3 |      100 |    95.92 |                   |
core-validate-commit           |      100 |      100 |      100 |      100 |                   |
index.js                      |      100 |      100 |      100 |      100 |                   |
core-validate-commit/lib       |    94.55 |       80 |      100 |    94.44 |                   | …
```
=> test: add tests for release commits

README.md
Update Travis CI badge to correct URL. Remove Coveralls, which hasn't
worked since this module was moved into the Node.js organization.
=> doc: update README.md badges

lib/rules/fixes-url.js, lib/rules/pr-url.js, test/rules/fixes-url.js, test/rules/pr-url.js
Refs: https://github.com/nodejs/node/pull/26691#issuecomment-476350154
e.g. for https://github.com/nodejs/node/commit/bdea725bdcb299579547f66ebcc98af16f53cd16
```console
-bash-4.2$ node ../core-validate-commit/bin/cmd.js bdea725
✖  bdea725bdcb299579547f66ebcc98af16f53cd16
✖  4:7      Fixes must be a GitHub URL.               fixes-url
✔  5:7      Valid fixes URL.                          fixes-url
✔  0:0      blank line after title                    line-after-title
✔  0:0      line-lengths are valid                    line-length
✔  0:0      metadata is at end of message             metadata-end
✔  3:8      PR-URL is valid.                          pr-url
✔  0:0      reviewers are valid                       reviewers
✔  0:0      valid subsystems                          subsystem
✔ …
```
=> Stricter URL checks

lib/rules/fixes-url.js, lib/rules/pr-url.js, test/rules/fixes-url.js, test/rules/pr-url.js
GitHub user and organization names and repository names can contain
hyphen characters which are not included in the `\w` regular
expression character class.
=> rules: allow GitHub URLs containing hyphens 

package.json
Do not pack tests into the npm package.
=> package.json: only pack necessary files

lib/rules/subsystem.js
`gyp:` has been used as subsystem tag 30 times for tools/gyp
See https://github.com/nodejs/node/pull/28573
=> subsystem: allow `gyp` as a subsystem

bin/cmd.js, bin/usage.txt, lib/utils.js, test/cli-test.js
This commit adds the flag --list-subsystems to list all the subsystems that are available for use.
fixes #66
Since the output is rather long is just listing in one column, so i'm using 3 columns when doing the listing.
=> bin: add a flag to list the subsystems

bin/cmd.js, lib/format-pretty.js, lib/rules/fixes-url.js, lib/rules/line-length.js, lib/rules/metadata-end.js, lib/rules/pr-url.js, lib/rules/subsystem.js
This replaces the usage of var with let to make the code more consistent.  This was something i noticed while working on #71
=> src:  Replace var with let

test/utils-test.js
* This adds tests for both the rightPad and leftPad utility function.
While going through #71  and #70 I noticed that this class was missing a couple test cases.
This should bring the test coverage up to 100% for those particular functions
=> test: add tests for padding util functions

test/utils-test.js
* This adds a test for the header utility function.
This one was a little interesting, since the outputs where being styled.  In the tests, i've stripped off the ansi encoding, since we aren't really trying to test that chalk worked, we are just interested in the "normal" string output
I'm sending this PR first, before i send the PR that tests the last 2 functions in this file, since they also have output styled with chalk.  And if what i did here is ok, then i'll send that one also
=> test: add tests for header util functions

test/rule-test.js
* This adds two tests for the Rules class testing the error conditions for when a rule does not have an id parameter or a validate function.
While going through #73 and #70 I noticed that this class was missing a couple test cases.
This should bring the test coverage up to 100% for that particular file
=> test: Add test for Rule class.

lib/rules/subsystem.js
Refs https://github.com/nodejs/node/pull/30094.
Adds `cli` to the list of valid subsystems.
cc @addaleax
=> lib: add cli to valid subsystems

lib/rules/subsystem.js
It would be useful to have a generic Web Assembly dedicated subsystem at this point, which also will allow us to handle WASI as well until we have its builtin name set.
=> lib: add wasm subsystem

bin/cmd.js, lib/format-pretty.js, lib/format-tap.js, lib/index.js, lib/rule.js, lib/rules/fixes-url.js, lib/rules/line-after-title.js, lib/rules/line-length.js, lib/rules/metadata-end.js, lib/rules/pr-url.js, lib/rules/reviewers.js, lib/rules/subsystem.js, lib/rules/title-format.js, lib/rules/title-length.js, lib/tap.js, lib/utils.js, package.json, test/cli-test.js, test/rule-test.js, test/rules/fixes-url.js, test/rules/line-after-title.js, test/rules/line-length.js, test/rules/pr-url.js, test/rules/reviewers.js, test/rules/subsystem.js, test/rules/title-format.js, test/utils-test.js, test/validator.js
Switches to using Standard rather than lintit, after noticing that the code style was relatively... different than most modern JavaScript I've seen.
Switching to Standard did require several bits of refactoring outside of the normal `standard --fix` to make the CLI compliant, including moving to `new URL()` rather than `url.parse()`, shifting around some inline functions, and tweaking a few of the RegEx (did my best to validate that they would still do what they should with external tooling in addition to running `npm run test`).
cc @codebytere
=> chore: use standard

lib/rules/subsystem.js
`n-api` shall no longer be accepted as a subsystem. Instead, the
accepted name for it shall be `node-api`.
Refs: https://github.com/nodejs/abi-stable-node/issues/420
=> lib: rename n-api to node-api

.github/workflows/node.js.yml, bin/cmd.js, test/cli-test.js
The refactoring done under https://github.com/nodejs/core-validate-commit/pull/84 introduced some regressions. Fix those and add tests.
- bin: fix URL parsing
`new URL()` throws an exception when failing to parse a URL.
- bin: wait for help output
The `help` module asynchronously pipes output to streams. Do not
explicitly `process.exit` to allow the asynchronous operation to
complete.
Refs: https://github.com/nodejs/core-validate-commit/pull/84
=> Fix regressions from refactoring

lib/rules/subsystem.js
Refs: https://github.com/nodejs/node/pull/38198
=> rules: add "typings" subsystem

lib/rules/co-authored-by-is-trailer.js, test/rules/co-authored-by-is-trailer.js
This rule ensures that `Co-authored-by` is a trailer and does not appear at the beginning of any non-trailer lines. Violations of this rule have caused some commits to not be attributed to co-authors in the core repository.
cc @nodejs/build @nodejs/node-core-utils
Refs: https://github.com/nodejs/node-core-utils/issues/602
=> rules: add co-authored-by-is-trailer

.github/workflows/node.js.yml
v10.x and v15.x are outdated. Remove those and add v16.x and v17.x instead.
=> chore: update tested node release lines

lib/tap.js, test/cli-test.js
If commit linting fails, include the URL to the commit message
guidelines in the TAP output.
Refs: https://github.com/nodejs/node/issues/41697
This will output, e.g. 
```
ok 1 co-authored-by-is-trailer: no Co-authored-by metadata
ok 2 fixes-url: skipping fixes-url # SKIP
ok 3 line-after-title: blank line after title
ok 4 line-length: line-lengths are valid
not ok 5 subsystem: Invalid subsystem: "feat" (feat: point to guidelines on failure in TAP output)
---
{
found: 'feat: point to guidelines on failure in TAP output',
compare: 'indexOf() !== -1',
wanted: [
'benchmark',      'build',    'bootstrap',   'cli',
'deps',           'doc',      'errors',      'etw',
'esm',            'gyp',      'inspector',   'lib',
'loader',         'meta',     'msi',         'node',
'node-api', …
```
=> feat: point to guidelines on failure in TAP output

lib/rules/subsystem.js
Refs: https://github.com/nodejs/node/pull/42325
=> rules: add `test_runner` subsystem

lib/rules/title-length.js, test/validator.js
This change ensures that the commit message linter doesn't reject
revert commits that originally had commit titles with an acceptable
length but were elongated during the revert process by running
`git revert`.
Fixes: https://github.com/nodejs/core-validate-commit/issues/97
Signed-off-by: Darshan Sen <raisinten@gmail.com>
=> rules: accept revert commit titles that were elongated by git

lib/rules/title-format.js, test/validator.js
The commit, https://github.com/nodejs/node/pull/45119/commits/cbb404503c9df13aaeb3dd8b345cb3f34c8c07e4, was being flagged as invalid by core-validate-commit because of this error:
```txt
Error: not ok 6 title-format: First word after subsystem(s) in title should be lowercase. (Revert "deps: V8: forward declaration of `Rtl*FunctionTable`")
```
This is incorrect because "deps: V8" is a valid subsystem. This change makes sure that revert commits with such a subsystem is accepted.
Signed-off-by: Darshan Sen <raisinten@gmail.com>
cc @targos
=> rules: accept "deps: V8" as the subsystem for revert commits

package.json
Coverage is not at 100% so `npm test` and `npm test-ci` will fail. Disabled coverage check (but coverage reporting will still happen).
=> fix: update tap@14 to tap@15

lib/rules/subsystem.js
Failing on https://github.com/nodejs/node/pull/46975
=> rules: add `permission` subsystem

lib/rules/subsystem.js
So that `sea: ...` can be used as the commit subjects of single-executable PRs in the https://github.com/nodejs/node repo.
cc @nodejs/single-executable
=> rules: add `sea` to subsystem

lib/rules/fixes-url.js, lib/rules/pr-url.js, test/rules/fixes-url.js, test/rules/pr-url.js
Refs: https://openjs-foundation.slack.com/archives/C019Y2T6STH/p1720463991463229
=> fix: support trailing slash

lib/rules/subsystem.js
Ref: https://github.com/nodejs/node/issues/53795#issuecomment-2219727938
Ref: https://github.com/nodejs/node/pull/53752
CC @targos
=> feat(sqlite): add `sqlite` subsystem
